spring.application.name=CrudSpringBoot
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/StudentCrud
spring.datasource.username=root
spring.datasource.password=prakharj@122005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

